# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/python-template",
        "doc_host": "https://real-analytics-rd.github.io",
        "git_url": "https://github.com/real-analytics-rd/python-template",
        "lib_path": "src/ra/python_template",
    },
    "syms": {"python_template.hello": {}},
}
