# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/python-template",
        "doc_host": "https://jlopezpena.github.io",
        "git_url": "https://github.com/jlopezpena/python-template",
        "lib_path": "src/jlp/python-template",
    },
    "syms": {},
}
