# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/skillcorner-ingestor",
        "doc_host": "https://real-analytics-rd.github.io",
        "git_url": "https://github.com/real-analytics-rd/skillcorner-ingestor",
        "lib_path": "src/ra/skillcorner",
    },
    "syms": {},
}
